### ISSUE TITLE
homework review completed

### ISSUE THREAD

**Issue by hatelove** [PhoenixChen2016/TDD_Homework1#1]
API 設計的不錯，建議除非必要場景，以這例子來說，避免使用 dynamic, 如上課中提到，建議將這個 domain entity 視為 Product 或 Order，因為這樣測試案例會更具備 domain/spec 的解釋能力。

**Comment by phoenix-chen-2016** [comment]
將dynamic修改成Order了

**Comment by hatelove** [comment]
看到您將取欄位名稱改成 nameof 的方式取，應該是為了避免 rename 所造成的問題，代表您有多想到這一層。

我這邊也提供我的 sample solution供您參考一下，有兩個版本，第一個版本只針對 Product, 第二個版本則是針對任意型別。http://bit.ly/91-tdd-day1-homework-solution

我是透過 generic + lambda + extension method 來處理任意型別+欄位名稱的問題，而且使用的呼叫端會輕鬆很多，語意也會清楚很多。
